name: ycnews
description: Client for HackerNews

version: 1.0.3+5

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  flutter_spinkit: ^4.1.1
  url_launcher: ^5.4.1
  shared_preferences: ^0.5.6+2
  webview_flutter: ^0.3.19+8
  package_info: ^0.4.0+14

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'

flutter:
  uses-material-design: true
